name: my_wallert
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.66.0
  intl: ^0.19.0
  firebase_core: ^3.13.0
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.3
  connectivity_plus: ^6.1.4
  cloud_firestore: ^5.6.7
  get_it: ^8.0.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true