// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnu9kFzduJvikVHl2hbp2h8QkBXEPaccc',
    appId: '1:233790611719:web:5eef83e3c5f2925c5ee5a2',
    messagingSenderId: '233790611719',
    projectId: 'expence-tracker-21990',
    authDomain: 'expence-tracker-21990.firebaseapp.com',
    storageBucket: 'expence-tracker-21990.firebasestorage.app',
    measurementId: 'G-PH7RBX2PVD',
    databaseURL: 'https://expence-tracker-21990-wallet-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbx50TZDG6S6xo3dieIAZV6I-wkklXOBE',
    appId: '1:233790611719:android:c0e12ed9ffa8bd345ee5a2',
    messagingSenderId: '233790611719',
    projectId: 'expence-tracker-21990',
    storageBucket: 'expence-tracker-21990.firebasestorage.app',
    databaseURL: 'https://expence-tracker-21990-wallet-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAri7C8w_ehm9Keem3syopizSHCQBQq780',
    appId: '1:233790611719:ios:a77a1db38e511aef5ee5a2',
    messagingSenderId: '233790611719',
    projectId: 'expence-tracker-21990',
    storageBucket: 'expence-tracker-21990.firebasestorage.app',
    androidClientId: '233790611719-436rk37vep2vq54vhhnlil8qnfgnael8.apps.googleusercontent.com',
    iosClientId: '233790611719-ikjhlatbjriovlqdjrobq8ba8cgmcrc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
    databaseURL: 'https://expence-tracker-21990-wallet-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAri7C8w_ehm9Keem3syopizSHCQBQq780',
    appId: '1:233790611719:ios:a77a1db38e511aef5ee5a2',
    messagingSenderId: '233790611719',
    projectId: 'expence-tracker-21990',
    storageBucket: 'expence-tracker-21990.firebasestorage.app',
    androidClientId: '233790611719-436rk37vep2vq54vhhnlil8qnfgnael8.apps.googleusercontent.com',
    iosClientId: '233790611719-ikjhlatbjriovlqdjrobq8ba8cgmcrc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
    databaseURL: 'https://expence-tracker-21990-wallet-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnu9kFzduJvikVHl2hbp2h8QkBXEPaccc',
    appId: '1:233790611719:web:20ffdb94deb8a8ce5ee5a2',
    messagingSenderId: '233790611719',
    projectId: 'expence-tracker-21990',
    authDomain: 'expence-tracker-21990.firebaseapp.com',
    storageBucket: 'expence-tracker-21990.firebasestorage.app',
    measurementId: 'G-765GHDYFBL',
    databaseURL: 'https://expence-tracker-21990-wallet-rtdb.firebaseio.com',
  );
}
